import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const root = resolve(process.cwd(), "..", "contracts", "deployments");
const outDir = resolve(process.cwd(), "src", "abi");

function loadDeployment(network, name) {
  try {
    const p = resolve(root, network, `${name}.json`);
    const j = JSON.parse(readFileSync(p, "utf-8"));
    return j;
  } catch {
    return null;
  }
}

function writeABI(abi) {
  const p = resolve(outDir, "ShapeDropChainABI.ts");
  writeFileSync(p, `// Auto-generated by scripts/genabi.mjs (run: npm run genabi)
export const ShapeDropChainABI = ${JSON.stringify(abi, null, 2)};
`);
}

function writeAddresses(map) {
  const p = resolve(outDir, "ShapeDropChainAddresses.ts");
  writeFileSync(p, `// Auto-generated by scripts/genabi.mjs (run: npm run genabi)
export const ShapeDropChainAddresses: Record<string, { address: \`0x\${string}\`; chainId: number; chainName: string }> = ${JSON.stringify(map, null, 2)};
`);
}

const local = loadDeployment("localhost", "ShapeDropChain");
const sepolia = loadDeployment("sepolia", "ShapeDropChain");

const addresses = {};
if (local?.address) {
  addresses["31337"] = { address: local.address, chainId: 31337, chainName: "hardhat" };
}
if (sepolia?.address) {
  addresses["11155111"] = { address: sepolia.address, chainId: 11155111, chainName: "sepolia" };
}

const abi = local?.abi || sepolia?.abi || [];
writeABI(abi);
writeAddresses(addresses);
console.log("ABI and addresses generated:", Object.keys(addresses));


