// Auto-generated by scripts/genabi.mjs (run: npm run genabi)
export const ShapeDropChainABI = [
  {
    "inputs": [],
    "name": "ZamaProtocolUnsupported",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EncryptedHistoryAppended",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "EncryptedMirrorUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "EncryptedPlayerAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "score",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lines",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "ScoreUpdated",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_LINES",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_SCORE",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "confidentialProtocolId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "getAllEncRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "user",
            "type": "address"
          },
          {
            "internalType": "euint32",
            "name": "scoreEnc",
            "type": "bytes32"
          },
          {
            "internalType": "euint32",
            "name": "linesEnc",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          }
        ],
        "internalType": "struct ShapeDropChain.EncWithUser[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "getAllRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "user",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "score",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "lines",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "difficulty",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          }
        ],
        "internalType": "struct ShapeDropChain.GameRecordWithUser[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getEncHistory",
    "outputs": [
      {
        "internalType": "euint32[]",
        "name": "scoreEnc",
        "type": "bytes32[]"
      },
      {
        "internalType": "euint32[]",
        "name": "linesEnc",
        "type": "bytes32[]"
      },
      {
        "internalType": "uint8[]",
        "name": "difficulty",
        "type": "uint8[]"
      },
      {
        "internalType": "uint256[]",
        "name": "timestamp",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getEncHistoryLength",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "getUserRecord",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "score",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "lines",
            "type": "uint256"
          },
          {
            "internalType": "uint8",
            "name": "difficulty",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          }
        ],
        "internalType": "struct ShapeDropChain.GameRecord",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "getUserRecordEnc",
    "outputs": [
      {
        "internalType": "euint32",
        "name": "scoreEnc",
        "type": "bytes32"
      },
      {
        "internalType": "euint32",
        "name": "linesEnc",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "score",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lines",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "submitScore",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "externalEuint32",
        "name": "scoreEnc",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "scoreProof",
        "type": "bytes"
      },
      {
        "internalType": "externalEuint32",
        "name": "linesEnc",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "linesProof",
        "type": "bytes"
      },
      {
        "internalType": "uint8",
        "name": "difficulty",
        "type": "uint8"
      }
    ],
    "name": "submitScoreEnc",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];
