// Auto-generated by scripts/genabi.mjs (run: npm run genabi)
export const ShapeDropChainAddresses: Record<string, { address: `0x${string}`; chainId: number; chainName: string }> = {
  "31337": {
    "address": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "chainId": 31337,
    "chainName": "hardhat"
  }
};
